[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "linker=D:/Software/scoop/apps/mingw/12.2.0-rt_v10-rev1/bin/gcc.exe"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "linker=D:/Software/scoop/apps/gcc-aarch64-none-linux-gnu/current/bin/aarch64-none-linux-gnu-gcc.exe"]