[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "linker=D:/Software/SysGCC/bin/x86_64-linux-gnu-gcc.exe", "-C", "target-feature=+crt-static"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "linker=D:/Software/scoop/apps/gcc-aarch64-none-linux-gnu/current/bin/aarch64-none-linux-gnu-gcc.exe"]

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "linker=D:/Software/aarch64-linux-musl/bin/aarch64-linux-musl-gcc.exe"]