[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "linker=x86_64-linux-gnu-gcc.exe", "-C", "target-feature=+crt-static"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "linker=aarch64-none-linux-gnu-gcc.exe"]

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "linker=aarch64-linux-musl-gcc.exe"]